# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6rvAUUPqCT11vDNg3OTZgT8e-1ACSnl
"""

import re
from google.colab import files
uploaded = files.upload()
for filename in uploaded.keys():
  print(f'User uploaded file "{filename}"')
  with open(filename, 'r') as f:
    content = f.read()
  numbers = re.findall(r'\d+', content)
  total_sum = sum(int(number) for number in numbers)
  print(f"The sum of all numbers in the file is: {total_sum}")

# prompt: To write algorithms for AddQ (enqueue) and DeleteQ (dequeue) assuming the queue is implemented using a linked list, write simple algorithim

Algorithm AddQ(item, list):
  1. Create a new node.
  2. Store the item in the new node.
  3. Set the next pointer of the new node to NULL.
  4. If the list is empty:
    a. Set the head and tail of the list to the new node.
  5. Else:
    a. Set the next pointer of the current tail node to the new node.
    b. Set the tail of the list to the new node.

Algorithm DeleteQ(list):
  1. If the list is empty:
    a. Return an error (queue underflow).
  2. Store the item in the head node as the returned item.
  3. Set the head of the list to the next node (head.next).
  4. If the list becomes empty after deletion:
    a. Set the tail of the list to NULL.
  5. Return the stored item.

import re
from google.colab import files

# Upload the text file
uploaded = files.upload()

# Assuming only one file was uploaded
for filename in uploaded.keys():
  print(f'User uploaded file "{filename}"')
  with open(filename, 'r') as f:
    content = f.read()

  # Find all numbers in the content using regex
  numbers = re.findall(r'\d+', content)

  # Convert the found numbers to integers and sum them
  total_sum = sum(int(number) for number in numbers)

  print(f"The sum of all numbers in the file is: {total_sum}")

import re
from google.colab import files

# Upload the text file
uploaded = files.upload()

# Assuming only one file was uploaded
for filename in uploaded.keys():
  print(f'User uploaded file "{filename}"')
  with open(filename, 'r') as f:
    content = f.read()

  # Find all numbers in the content using regex
  numbers = re.findall(r'\d+', content)

  # Convert the found numbers to integers
  numbers_int = [int(number) for number in numbers]

  # Print each number
  for num in numbers_int:
    print(num)

  # Calculate and print the sum
  total_sum = sum(numbers_int)
  print(f"Sum: {total_sum}")

# prompt: now write a code such that when one folder is uploaded or inserted by me which has multiple text files , each text files ka sum to be added similar to above and then all sums to be added in end as one sum , I SHOULD BE ABLE TO UPLOAD FOLDER

import re
import os
from google.colab import files

# The files.upload() function uploads individual files, not folders directly.
# To handle a folder upload, you would typically upload a zip file
# or instruct the user to select multiple files.
# The following code assumes the user will select multiple text files
# when prompted by files.upload().

uploaded = files.upload()

overall_total_sum = 0

for filename in uploaded.keys():
  print(f'Processing file "{filename}"')
  # You can optionally save the uploaded files to a directory
  # For this example, we'll process them directly from the uploaded dictionary
  # with open(filename, 'wb') as f:
  #   f.write(uploaded[filename])

  try:
    # Decode the file content assuming it's a text file
    content = uploaded[filename].decode('utf-8')

    # Find all numbers in the content using regex
    numbers = re.findall(r'\d+', content)

    # Convert the found numbers to integers and sum them for the current file
    file_sum = sum(int(number) for number in numbers)
    print(f"The sum of all numbers in '{filename}' is: {file_sum}")

    # Add the file sum to the overall total sum
    overall_total_sum += file_sum

  except Exception as e:
    print(f"Error processing file {filename}: {e}")

print(f"\nOverall sum of numbers across all files: {overall_total_sum}")