# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6rvAUUPqCT11vDNg3OTZgT8e-1ACSnl
"""

# prompt: To write algorithms for AddQ (enqueue) and DeleteQ (dequeue) assuming the queue is implemented using a linked list, write simple algorithim

Algorithm AddQ(item, list):
  1. Create a new node.
  2. Store the item in the new node.
  3. Set the next pointer of the new node to NULL.
  4. If the list is empty:
    a. Set the head and tail of the list to the new node.
  5. Else:
    a. Set the next pointer of the current tail node to the new node.
    b. Set the tail of the list to the new node.

Algorithm DeleteQ(list):
  1. If the list is empty:
    a. Return an error (queue underflow).
  2. Store the item in the head node as the returned item.
  3. Set the head of the list to the next node (head.next).
  4. If the list becomes empty after deletion:
    a. Set the tail of the list to NULL.
  5. Return the stored item.

import re
from google.colab import files

# Upload the text file
uploaded = files.upload()

# Assuming only one file was uploaded
for filename in uploaded.keys():
  print(f'User uploaded file "{filename}"')
  with open(filename, 'r') as f:
    content = f.read()

  # Find all numbers in the content using regex
  numbers = re.findall(r'\d+', content)

  # Convert the found numbers to integers and sum them
  total_sum = sum(int(number) for number in numbers)

  print(f"The sum of all numbers in the file is: {total_sum}")

import re
from google.colab import files

# Upload the text file
uploaded = files.upload()

# Assuming only one file was uploaded
for filename in uploaded.keys():
  print(f'User uploaded file "{filename}"')
  with open(filename, 'r') as f:
    content = f.read()

  # Find all numbers in the content using regex
  numbers = re.findall(r'\d+', content)

  # Convert the found numbers to integers
  numbers_int = [int(number) for number in numbers]

  # Print each number
  for num in numbers_int:
    print(num)

  # Calculate and print the sum
  total_sum = sum(numbers_int)
  print(f"Sum: {total_sum}")

# prompt: is the above two codes python?

Yes, the code provided in the previous responses is Python.

In the file you provided, the parts within the code blocks (`import re`, `from google.colab import files`, and the code following the queue algorithms) are Python code.

The sections describing the `Algorithm AddQ` and `Algorithm DeleteQ` are not Python code. They are written in a pseudocode format, which is used to describe algorithms in a way that is easy for humans to understand, independent of any specific programming language.